-- MySQL Script generated by MySQL Workbench
-- 08/23/15 12:03:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TNT_Exam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TNT_Exam` ;

-- -----------------------------------------------------
-- Schema TNT_Exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TNT_Exam` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `TNT_Exam` ;

-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(20) NULL COMMENT '',
  `Nombre` VARCHAR(150) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Password` VARCHAR(45) NOT NULL COMMENT '',
  `FechaNacimiento` DATE NULL COMMENT '',
  `UserName` VARCHAR(45) NOT NULL COMMENT '',
  `idPerfil` INT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Materias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Materias` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idMateria`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Temas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Temas` (
  `idTema` INT NOT NULL AUTO_INCREMENT,
  `idMateria` INT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Materias_idMateria` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTema`, `Materias_idMateria`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Complejidads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Complejidads` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Complejidads` (
  `idComplejidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Descripcion` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`idComplejidad`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TipoPreguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoPreguntas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TipoPreguntas` (
  `idTipoPreguntas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Descripcion` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`idTipoPreguntas`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Preguntas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Preguntas` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `idTema` INT NULL COMMENT '',
  `idTipoPregunta` INT NULL COMMENT '',
  `idComplegidad` INT NULL COMMENT '',
  `Pregunta` VARCHAR(500) NULL COMMENT '',
  `Temas_idTema` INT NOT NULL COMMENT '',
  `Temas_Materias_idMateria` INT NOT NULL COMMENT '',
  `Complejidads_idComplejidad` INT NOT NULL COMMENT '',
  `TipoPreguntas_idTipoPreguntas` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPregunta`, `Temas_idTema`, `Temas_Materias_idMateria`, `Complejidads_idComplejidad`, `TipoPreguntas_idTipoPreguntas`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Respuestas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Respuestas` (
  `idRespuestas` INT NOT NULL AUTO_INCREMENT,
  `idPregunta` INT NULL COMMENT '',
  `Respuesta` VARCHAR(300) NULL COMMENT '',
  `Correcta` BIT NULL COMMENT '',
  `Preguntas_idPregunta` INT NOT NULL COMMENT '',
  `Preguntas_Temas_idTema` INT NOT NULL COMMENT '',
  `Preguntas_Temas_Materias_idMateria` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idRespuestas`, `Preguntas_idPregunta`, `Preguntas_Temas_idTema`, `Preguntas_Temas_Materias_idMateria`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Examenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examenes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Examenes` (
  `idExamen` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `CantidadPreguntas` INT NULL COMMENT '',
  `Estado` BIT NULL COMMENT '',
  PRIMARY KEY (`idExamen`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DescripcionExamenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DescripcionExamenes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `DescripcionExamenes` (
  `idDescripcionExamen` INT NOT NULL AUTO_INCREMENT,
  `idExamen` INT NULL COMMENT '',
  `idPregunta` INT NULL COMMENT '',
  `CantidadPreguntaTema` INT NULL COMMENT '',
  `Porcentage` DOUBLE NULL COMMENT '',
  `Examenes_idExamen` INT NOT NULL COMMENT '',
  `Preguntas_idPregunta` INT NOT NULL COMMENT '',
  `Preguntas_Temas_idTema` INT NOT NULL COMMENT '',
  `Preguntas_Temas_Materias_idMateria` INT NOT NULL COMMENT '',
  `Preguntas_Complejidads_idComplejidad` INT NOT NULL COMMENT '',
  `Preguntas_TipoPreguntas_idTipoPreguntas` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDescripcionExamen`, `Examenes_idExamen`, `Preguntas_idPregunta`, `Preguntas_Temas_idTema`, `Preguntas_Temas_Materias_idMateria`, `Preguntas_Complejidads_idComplejidad`, `Preguntas_TipoPreguntas_idTipoPreguntas`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `Complejidads`
-- -----------------------------------------------------
START TRANSACTION;
USE `TNT_Exam`;
INSERT INTO `Complejidads` (`idComplejidad`, `Nombre`, `Descripcion`) VALUES (DEFAULT, 'Facil', 'Facil');
INSERT INTO `Complejidads` (`idComplejidad`, `Nombre`, `Descripcion`) VALUES (DEFAULT, 'Normal', 'Normal');
INSERT INTO `Complejidads` (`idComplejidad`, `Nombre`, `Descripcion`) VALUES (DEFAULT, 'Dificil', 'Dificil');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
